/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kelas;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        BicycleDemo bicycleDemo = new BicycleDemo();
        
    }
}
