/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package depedencyInject;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
