/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bject;

public class App {
    public String getGreeting() {

        String a ="Gajah";
        String b = "Semut";
        
        return a +" dan "+ b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
